# Generated by Django 3.0.5 on 2020-04-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20200414_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.AddField(
            model_name='photo',
            name='PICOIN',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
