# Generated by Django 3.0.5 on 2020-04-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20200427_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='PICOIN',
            field=models.PositiveIntegerField(default=0, verbose_name='PICOIN'),
        ),
    ]
