# Generated by Django 3.0.5 on 2020-04-27 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20200427_2048'),
        ('core', '0002_auto_20200425_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicoInfoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile', verbose_name='PROFILE')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoicoInfoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Photo', verbose_name='PHOTO')),
            ],
        ),
    ]
