# Generated by Django 3.0.5 on 2020-04-28 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20200428_1617'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_photoicoinfolog_profilepicoinfolog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoicoinfolog',
            options={'ordering': ('-donate_dt',)},
        ),
        migrations.AlterModelOptions(
            name='profilepicoinfolog',
            options={'ordering': ('-donate_dt',)},
        ),
        migrations.AddField(
            model_name='photoicoinfolog',
            name='PICOIN',
            field=models.PositiveIntegerField(default=0, verbose_name='PICOIN'),
        ),
        migrations.AddField(
            model_name='photoicoinfolog',
            name='donate_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Donation Datetime'),
        ),
        migrations.AddField(
            model_name='photoicoinfolog',
            name='donator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='DONATOR'),
        ),
        migrations.AddField(
            model_name='profilepicoinfolog',
            name='PICOIN',
            field=models.PositiveIntegerField(default=0, verbose_name='PICOIN'),
        ),
        migrations.AddField(
            model_name='profilepicoinfolog',
            name='donate_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Donation Datetime'),
        ),
        migrations.AddField(
            model_name='profilepicoinfolog',
            name='donator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='DONATOR'),
        ),
        migrations.AddField(
            model_name='profilepicoinfolog',
            name='where',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='photo.Photo', verbose_name='WHERE'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='PICOIN',
            field=models.PositiveIntegerField(default=0, verbose_name='PICOIN'),
        ),
    ]
